#!/bin/bash

disk_dev=sdb
disk_num_array=(1 5 6 7 8)
disk_name_array=('System' 'Setup' 'Study' 'Private' 'Happy')

echo "-- Mount all locate disks to this path --"

for num in {0..4}
do 
    disk_num=${disk_num_array[$num]}
    disk_name=${disk_name_array[$num]}

    test -d $disk_name || mkdir $disk_name
    ntfs-3g /dev/${disk_dev}${disk_num} $disk_name && echo " Created $disk_name/" 
done

echo "-- Done --"
