#!/bin/sh

disk_name_array=('System' 'Setup' 'Study' 'Private' 'Happy')

echo "-- Umount all disks from this path --"

for num in {0..4}
do 
    disk_name=${disk_name_array[$num]}
    umount $disk_name && rm -rf $disk_name && echo " Removed $disk_name/"
done

echo "-- Done --"
